"""
agents/github_docs/docs_agent.py — GitHub Docs & Profile Automation main orchestrator.

Tasks (per SYSTEM_DESIGN.md Section 10):
  1. Daily: Aggregate agent outputs and commit non-sensitive artifacts
  2. Weekly: Generate weekly report (docs/reports/week_YYYY_WW.md)
  3. Weekly: Update CHANGELOG.md
  4. Weekly: Update GitHub profile README

Entry points:
  run()               — Full daily/weekly docs run
  get_recent_commits() — Return recent commits across tracked repos (for /commits command)
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from shared.logger import get_logger
from shared.db import get_conn, get_db_path, log_health
from shared.config_loader import load_config

log = get_logger("github_docs")


def _send_telegram(message: str) -> None:
    try:
        import requests
        from shared.secrets import get_secret
        token = get_secret("TELEGRAM_BOT_TOKEN")
        chat_id = get_secret("TELEGRAM_CHAT_ID")
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception as e:
        log.warning("telegram_send_failed", error=str(e))


def _generate_weekly_report(dry_run: bool = False) -> str:
    """Generate and write the weekly markdown report."""
    cfg = load_config()
    now = datetime.now()
    year, week = now.year, now.isocalendar()[1]

    report_path_template = cfg.documentation_and_github.docs_convention.weekly_report
    report_path = _REPO_ROOT / report_path_template.replace("YYYY", str(year)).replace("WW", f"{week:02d}")
    report_path.parent.mkdir(parents=True, exist_ok=True)

    # Gather stats
    stats = _gather_stats()

    # Use Jinja2 template if available
    template_path = Path(__file__).parent / "report_templates" / "weekly_report.md.jinja"
    if template_path.exists():
        try:
            from jinja2 import Template
            template = Template(template_path.read_text(encoding="utf-8"))
            content = template.render(year=year, week=week, now=now, stats=stats, cfg=cfg)
        except Exception as e:
            log.warning("jinja_render_failed", error=str(e))
            content = _fallback_report(year, week, stats, cfg)
    else:
        content = _fallback_report(year, week, stats, cfg)

    if not dry_run:
        report_path.write_text(content, encoding="utf-8")
        log.info("weekly_report_written", path=str(report_path))

    return content


def _fallback_report(year: int, week: int, stats: dict, cfg) -> str:
    """Simple fallback weekly report without Jinja2."""
    now = datetime.now().strftime("%Y-%m-%d")
    return f"""# Weekly Automation Report — Week {week}, {year}
Generated: {now}

## Job Search
- Jobs discovered this week: {stats.get('jobs_week', 0)}
- Top score this week: {stats.get('top_score', 'N/A')}
- Pending applications: {stats.get('jobs_pending', 0)}

## Outreach
- Emails sent this week: {stats.get('outreach_week', 0)}
- Replies received: {stats.get('replies_week', 0)}
- Pending approval: {stats.get('outreach_pending', 0)}

## Resume Tailoring
- Variants generated: {stats.get('resumes_week', 0)}

## AI Radar
- Items processed: {stats.get('radar_week', 0)}
- TRY_NOW items: {stats.get('radar_try_asap', 0)}

---
*Generated by {cfg.profile.name}'s automation system*
"""


def _gather_stats() -> dict[str, Any]:
    """Gather weekly stats from SQLite."""
    stats: dict[str, Any] = {}
    try:
        with get_conn(get_db_path()) as conn:
            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM jobs WHERE date(created_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["jobs_week"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT MAX(score) as max_score FROM jobs WHERE date(created_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["top_score"] = f"{row['max_score']:.1f}/10" if row and row["max_score"] else "N/A"

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM jobs WHERE status = 'new'"
            ).fetchone()
            stats["jobs_pending"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM outreach WHERE date(sent_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["outreach_week"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM outreach WHERE status = 'pending_approval'"
            ).fetchone()
            stats["outreach_pending"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM outreach WHERE reply_received = 1 AND date(reply_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["replies_week"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM resumes WHERE date(created_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["resumes_week"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM ai_radar WHERE date(created_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["radar_week"] = row["cnt"] if row else 0

            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM ai_radar WHERE action_tag = 'TRY_ASAP' AND date(created_at) >= date('now', '-7 days')"
            ).fetchone()
            stats["radar_try_asap"] = row["cnt"] if row else 0

    except Exception as e:
        log.warning("stats_gather_failed", error=str(e))

    return stats


def _commit_artifacts(dry_run: bool = False) -> bool:
    """Commit non-sensitive artifacts to the automation repo."""
    try:
        from agents.github_docs.commit_scanner import validate_before_commit

        # Files to commit
        committable_patterns = [
            "docs/reports/*.md",
            "docs/ai_tools_radar_*.md",
            "assets/resumes/index.json",
            "CHANGELOG.md",
        ]

        files_to_add = []
        for pattern in committable_patterns:
            files_to_add.extend(_REPO_ROOT.glob(pattern))

        if not files_to_add:
            log.info("no_artifacts_to_commit")
            return True

        # Security scan before commit
        validate_before_commit(files_to_add)

        if dry_run:
            log.info("commit_dry_run", files=len(files_to_add))
            return True

        # Git add + commit
        for f in files_to_add:
            subprocess.run(["git", "add", str(f)], cwd=str(_REPO_ROOT), capture_output=True)

        result = subprocess.run(
            ["git", "commit", "-m", f"chore(docs): daily artifact commit [{datetime.now().strftime('%Y-%m-%d')}]"],
            cwd=str(_REPO_ROOT),
            capture_output=True, text=True,
        )

        if result.returncode == 0:
            log.info("artifacts_committed", files=len(files_to_add))
            return True
        else:
            log.warning("commit_failed", stderr=result.stderr[:200])
            return False

    except Exception as e:
        log.error("commit_artifacts_failed", error=str(e))
        return False


def get_recent_commits() -> str:
    """
    Return recent commits across tracked repos for the /commits Telegram command.
    Called by orchestrator.py cmd_commits().
    """
    cfg = load_config()
    from agents.github_docs.commit_scanner import get_recent_commits_text

    lines = ["📝 *Recent Commits*\n"]
    for repo_name in cfg.documentation_and_github.primary_repos:
        # Try to find local path
        repo_path = _REPO_ROOT.parent / repo_name
        if not repo_path.exists():
            repo_path = _REPO_ROOT  # Fall back to automation repo itself

        commits = get_recent_commits_text(repo_path, limit=5)
        if commits:
            lines.append(f"*{repo_name}:*")
            lines.extend(f"  `{line}`" for line in commits.split("\n")[:3])
            lines.append("")

    if len(lines) <= 1:
        return "📝 No recent commits found."
    return "\n".join(lines)


def run(dry_run: bool = False) -> str:
    """
    Full GitHub docs agent run.

    Args:
        dry_run: Skip file writes and git commits.

    Returns:
        Summary string for Telegram.
    """
    log.info("github_docs_start", dry_run=dry_run)
    cfg = load_config()
    start_time = datetime.now(timezone.utc)
    results = []

    # --- Update CHANGELOG ---
    try:
        from agents.github_docs.changelog_updater import (
            generate_changelog_entries_from_agents, update_changelog
        )
        entries = generate_changelog_entries_from_agents()
        update_changelog(entries, dry_run=dry_run)
        results.append(f"✅ CHANGELOG: {len(entries)} entries added")
    except Exception as e:
        results.append(f"❌ CHANGELOG: {e}")
        log.error("changelog_failed", error=str(e))

    # --- Generate weekly report ---
    try:
        _generate_weekly_report(dry_run=dry_run)
        now = datetime.now()
        results.append(f"✅ Weekly report: Week {now.isocalendar()[1]}, {now.year}")
    except Exception as e:
        results.append(f"❌ Weekly report: {e}")
        log.error("weekly_report_failed", error=str(e))

    # --- Update profile README (weekly only) ---
    try:
        if datetime.now().weekday() == 6 or True:  # Always update for now
            from agents.github_docs.readme_updater import update_profile_readme
            readme_result = update_profile_readme(dry_run=dry_run)
            results.append(f"✅ Profile README: updated")
    except Exception as e:
        results.append(f"❌ Profile README: {e}")
        log.error("readme_update_failed", error=str(e))

    # --- Commit artifacts ---
    try:
        committed = _commit_artifacts(dry_run=dry_run)
        results.append(f"✅ Git commit: {'done' if committed else 'skipped'}")
    except Exception as e:
        results.append(f"❌ Git commit: {e}")

    # --- Log health ---
    duration = (datetime.now(timezone.utc) - start_time).total_seconds()
    summary = f"GitHub Docs complete in {duration:.1f}s"
    with get_conn(get_db_path()) as conn:
        log_health(conn, "github_docs", "green", summary, {"duration_seconds": duration})

    log.info("github_docs_complete", duration=duration)
    full_result = "📚 *GitHub Docs Update*\n\n" + "\n".join(results)
    _send_telegram(full_result)
    return full_result
