"""
agents/market_research/reporter.py — Generate and deliver market research report.

Outputs:
  - Notion page (via notion_writer.py)
  - GitHub markdown report (docs/reports/)
  - Telegram Sunday digest
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from shared.logger import get_logger
from shared.db import get_conn, get_db_path, init_db, log_health
from shared.config_loader import load_config

log = get_logger("market_research")


def _send_telegram(message: str) -> None:
    try:
        import requests
        from shared.secrets import get_secret
        token = get_secret("TELEGRAM_BOT_TOKEN")
        chat_id = get_secret("TELEGRAM_CHAT_ID")
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception as e:
        log.warning("telegram_send_failed", error=str(e))


def _build_telegram_digest(analysis: dict[str, Any]) -> str:
    """Build a concise Telegram digest from the analysis."""
    cfg = load_config()
    max_items = cfg.research_and_discovery.summary_max_items
    week_num = datetime.now().isocalendar()[1]

    lines = [f"🧠 *Market Intelligence — Week {week_num}*\n"]

    summary = analysis.get("summary", "")
    if summary:
        lines.append(summary)
        lines.append("")

    trending = analysis.get("trending_tools", [])
    if trending:
        lines.append(f"🔥 *Trending:* {', '.join(trending[:5])}\n")

    build_next = analysis.get("build_next", [])
    if build_next:
        lines.append("🏗 *Build Next:*")
        for item in build_next[:3]:
            score = item.get("relevance_score", 0)
            emoji = "⭐" if score >= 0.8 else "•"
            lines.append(f"  {emoji} {item.get('project', '')} ({item.get('effort', '')})")
        lines.append("")

    skill_gaps = analysis.get("skill_gaps", [])
    high_priority = [g for g in skill_gaps if g.get("urgency") == "high"]
    if high_priority:
        lines.append("📈 *Rising Skill Gaps:*")
        for gap in high_priority[:3]:
            lines.append(f"  • {gap.get('skill', '')} — {gap.get('why', '')[:60]}")

    return "\n".join(lines)


def _write_markdown_report(analysis: dict[str, Any]) -> Path:
    """Write market research report as markdown to docs/."""
    cfg = load_config()
    now = datetime.now()
    year, week = now.year, now.isocalendar()[1]

    report_dir = _REPO_ROOT / "docs" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"market_research_{year}_W{week:02d}.md"

    summary = analysis.get("summary", "")
    build_next = analysis.get("build_next", [])
    apply_here = analysis.get("apply_here", [])
    skill_gaps = analysis.get("skill_gaps", [])
    trending = analysis.get("trending_tools", [])

    content = f"""# Market Research — Week {week}, {year}
Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}

## Summary

{summary}

## Trending Tools This Week

{chr(10).join(f'- {t}' for t in trending)}

## What to Build Next

{chr(10).join(f'- **{b.get("project", "")}** ({b.get("effort", "")}) — {b.get("why", "")}' for b in build_next)}

## Where to Apply

{chr(10).join(f'- **{a.get("company", "")}** — {a.get("reason", "")}' for a in apply_here)}

## Growing Skill Gaps

{chr(10).join(f'- [{g.get("urgency", "").upper()}] **{g.get("skill", "")}** — {g.get("why", "")}' for g in skill_gaps)}

---
*Generated by {cfg.profile.name}'s automation system*
"""

    report_path.write_text(content, encoding="utf-8")
    log.info("market_report_written", path=str(report_path))
    return report_path


def generate_report(analysis: dict[str, Any], dry_run: bool = False) -> str:
    """
    Generate and deliver the market research report.

    Args:
        analysis: Output from analyzer.analyze_market().
        dry_run: Skip Telegram and Notion writes.

    Returns:
        Summary string.
    """
    log.info("reporter_start", dry_run=dry_run)
    start_time = datetime.now(timezone.utc)
    results = []

    # Write markdown report
    try:
        report_path = _write_markdown_report(analysis)
        results.append(f"✅ Markdown report: {report_path.name}")
    except Exception as e:
        results.append(f"❌ Markdown report: {e}")

    # Write to Notion
    try:
        from agents.market_research.notion_writer import write_to_notion
        notion_url = write_to_notion(analysis, dry_run=dry_run)
        results.append(f"✅ Notion: {notion_url[:50]}")
    except Exception as e:
        results.append(f"❌ Notion: {e}")

    # Send Telegram digest
    if not dry_run:
        try:
            digest = _build_telegram_digest(analysis)
            _send_telegram(digest)
            results.append("✅ Telegram digest sent")
        except Exception as e:
            results.append(f"❌ Telegram: {e}")

    # Log health
    duration = (datetime.now(timezone.utc) - start_time).total_seconds()
    db_path = get_db_path()
    init_db(db_path)
    with get_conn(db_path) as conn:
        log_health(conn, "market_research", "green", "weekly report generated", {
            "duration_seconds": duration,
        })

    return "📊 *Market Research Complete*\n\n" + "\n".join(results)
